version: "3.9"

services:

# POSTGRESPRISMA
  postgresprisma:
    image: postgres:15.2-alpine
    container_name: postgresprisma
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes: 
      # - postgres:/var/lib/postgresql/data
      - ./data/drawSQL-pgsql-export-2023-02-24.sql:/docker-entrypoint-initdb.d/drawSQL-pgsql-export-2023-02-24.sql
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
  
  # WEB
  web:
    container_name: kanban
    build:
      context: ./
    depends_on:
      - postgresprisma
    volumes:
      - ./src:/home/node/app/src
      - ./static:/home/node/app/static
      - ./vite.config.js:/home/node/app/vite.config.js
      - ./tsconfig.json:/home/node/app/tsconfig.json
      - ./svelte.config.js:/home/node/app/svelte.config.js
      - ./tests:/home/node/app/tests
      - ./playwright.config.ts:/home/node/app/playwright.config.ts
      # - /home/node/app/node_modules
      # - .:/home/node/app
    
    ports:
      - "5173:5173"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    # environment:
      # DB_USER: ${DB_USER}
      # DB_PASSWORD: ${DB_PASSWORD}
      # DB_NAME: ${DB_NAME}
      # DATABASE_URL: "postgresql://postgres:postgres@db:5432/mydb?schema=public"
    # links:
    #   - db
    command:
      - /bin/sh
      - -c
      - |
        npx prisma generate
        npx prisma migrate dev --name init
        npm run dev
# volumes:
#   postgres:

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
#     driver: local
    # command: sh -c "npm install && npm run dev"
    # environment:
    #   - PORT=5173
    #   - HOST=0.0.0.0