version: "3.9"

services:
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      # - db:/var/lib/postgresql/data
      - ./data/drawSQL-pgsql-export-2023-02-24.sql:/docker-entrypoint-initdb.d/drawSQL-pgsql-export-2023-02-24.sql
  client:
    build:
      context: ./
    depends_on:
      - db
    volumes:
      - ./src:/home/node/app/src
      - ./static:/home/node/app/static
      - ./vite.config.js:/home/node/app/vite.config.js
      - ./tsconfig.json:/home/node/app/tsconfig.json
      - ./svelte.config.js:/home/node/app/svelte.config.js
      - ./tests:/home/node/app/tests
      - ./playwright.config.ts:/home/node/app/playwright.config.ts
      # - /home/node/app/node_modules
      # - .:/home/node/app
    ports:
      - "5173:5173"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
      - db
    command: npm run dev
# volumes:
#   db:
#     driver: local
    # command: sh -c "npm install && npm run dev"
    # environment:
    #   - PORT=5173
    #   - HOST=0.0.0.0