version: "3.9"

services:

  db:
    container_name: postgres
    image: postgres
    ports:
      - '5433:5432'
    volumes: 
      # - postgres:/var/lib/postgresql/data
      - ./data/drawSQL-pgsql-export-2023-02-24.sql:/docker-entrypoint-initdb.d/drawSQL-pgsql-export-2023-02-24.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  client:
    build:
      context: ./
    volumes:
      - ./src:/home/node/app/src
      - ./static:/home/node/app/static
      - ./vite.config.js:/home/node/app/vite.config.js
      - ./tsconfig.json:/home/node/app/tsconfig.json
      - ./svelte.config.js:/home/node/app/svelte.config.js
      - ./tests:/home/node/app/tests
      - ./playwright.config.ts:/home/node/app/playwright.config.ts
      # - /home/node/app/node_modules
      # - .:/home/node/app
    ports:
      - "5172:5173"
    depends_on:
      - db
    command: npm run dev

  # volumes: 
  #   data: {}
    # command: sh -c "npm install && npm run dev"
    # environment:
    #   - PORT=5173
    #   - HOST=0.0.0.0